FROM ubuntu:22.04

RUN apt -y update && apt -y upgrade && \
    apt -y install --no-install-recommends \
    ca-certificates && \
    apt -y clean && \
    rm -rf /var/lib/apt/lists/*

RUN update-ca-certificates -f

RUN apt -y update
RUN apt -y upgrade
RUN apt install -y --no-install-recommends \
    build-essential \
    cmake \
    libgtk2.0-dev \
    libpng-dev \
    libjpeg-dev \
    libopenexr-dev \
    libtiff-dev \
    libwebp-dev \
    pkg-config \
    python3-dev \
    python3-numpy \
    python3-pip \
    wget && \
    apt -y clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home


